## =========================================== - Drug API - =========================================

### create drug -----------------

POST http://localhost:3000/api/drugs/create
Content-Type: application/json
Accept: application/json
Authorization: c8d222ee-52c4-477e-80da-e7e81cfd10ae

{
    "name": "Cataplam",
    "price": 7500,
    "description": "Obat pereda sakit gigi"
}

### get drug -----------------

GET http://localhost:3000/api/drugs/4
Content-Type: application/json
Accept: application/json
Authorization: c8d222ee-52c4-477e-80da-e7e81cfd10ae

### update drug -----------------

PUT http://localhost:3000/api/drugs/1
Content-Type: application/json
Accept: application/json
Authorization: c8d222ee-52c4-477e-80da-e7e81cfd10ae

{
    "name": "Actifed",
    "price": 4500,
    "description": "Obat keras, butuh anjuran dokter"
}

### search drug -----------------

GET http://localhost:3000/api/drugs
Content-Type: application/json
Accept: application/json
Authorization: c8d222ee-52c4-477e-80da-e7e81cfd10ae

### delete drug -----------------

DELETE http://localhost:3000/api/drugs/2
Content-Type: application/json
Accept: application/json
Authorization: c8d222ee-52c4-477e-80da-e7e81cfd10ae