# =========================================== - MEdicalRec API - =========================================


### login doctor -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### create Medical Record -----------------

POST http://localhost:3000/api/medical-records/1
Content-Type: application/json
Accept: application/json
Authorization: 870f305a-0c3c-4de9-b946-b63fac2a7460

{
    "problem": "Panas tinggi",
    "diagnosis": "Gejala Tipes",
    "note": "Ini adalah catatan gejala tipes",
    "drugItems": [
        {"drugSelectedId": 4},
        {"drugSelectedId": 1}
    ]
}

### Get all Medical Record -----------------

GET http://localhost:3000/api/medical-records
Content-Type: application/json
Accept: application/json
Authorization: 870f305a-0c3c-4de9-b946-b63fac2a7460

### Get detail Medical Record -----------------

GET http://localhost:3000/api/medical-records/25
Content-Type: application/json
Accept: application/json
Authorization: 870f305a-0c3c-4de9-b946-b63fac2a7460

### update Medical Record -----------------

PUT http://localhost:3000/api/medical-records/13
Content-Type: application/json
Accept: application/json
Authorization: 870f305a-0c3c-4de9-b946-b63fac2a7460

{
    "problem": "Sesak nafas",
    "diagnosis": "Pemompa darah kurang maksimal berfungsi",
    "note": "Ini adalah catatan penyakit jantung",
    "drugItems": [
        {"drugSelectedId": 2},
        {"drugSelectedId": 3}
    ]
}

### Delete Medical records -----------------

DELETE http://localhost:3000/api/medical-records/6
Content-Type: application/json
Accept: application/json
Authorization: 870f305a-0c3c-4de9-b946-b63fac2a7460

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: f20e3afb-eadf-4652-bd6e-f4a6b33674ae