# =========================================== - MEdicalRec API - =========================================


### login doctor -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### create Medical Record -----------------

POST http://localhost:3000/api/medical-records/3
Content-Type: application/json
Accept: application/json
Authorization: 5328135c-3c3b-4222-b425-ff8655461319

{
    "problem": "Darah rendah",
    "diagnosis": "Jantung lemah memompa darah",
    "note": "Ini adalah catatan penyakit jantung",
    "drugItems": [
        {"drugSelectedId": 1}
    ]
}

### Get all Medical Record -----------------

GET http://localhost:3000/api/medical-records
Content-Type: application/json
Accept: application/json
Authorization: 5328135c-3c3b-4222-b425-ff8655461319

### Get detail Medical Record -----------------

GET http://localhost:3000/api/medical-records/16
Content-Type: application/json
Accept: application/json
Authorization: 5328135c-3c3b-4222-b425-ff8655461319

### update Medical Record -----------------

PUT http://localhost:3000/api/medical-records/16
Content-Type: application/json
Accept: application/json
Authorization: 5328135c-3c3b-4222-b425-ff8655461319

{
    "problem": "Sesak nafas",
    "diagnosis": "Pemompa darah kurang maksimal berfungsi",
    "note": "Ini adalah catatan penyakit jantung",
    "drugItems": [
        {"drugSelectedId": 2},
        {"drugSelectedId": 3}
    ]
}

### Delete Medical records -----------------

DELETE http://localhost:3000/api/medical-records/6
Content-Type: application/json
Accept: application/json
Authorization: 5328135c-3c3b-4222-b425-ff8655461319

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: f20e3afb-eadf-4652-bd6e-f4a6b33674ae