# =========================================== - MEdicalRec API - =========================================


### login doctor -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### create Medical Record -----------------

POST http://localhost:3000/api/medical-records/1
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a

{
    "problem": "Gusi Bengkak",
    "diagnosis": "Gejala penumbuhan gigi bungsu",
    "note": "Ini adalah catatan penyakit gejala gigi bungsu tumbuh",
    "drugId": 1
}

### Get all Medical Record -----------------

GET http://localhost:3000/api/medical-records
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a

### Get detail Medical Record -----------------

GET http://localhost:3000/api/medical-records/4
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a

### update Medical Record -----------------

PUT http://localhost:3000/api/medical-records/5
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a

{
    "problem": "Gagal jantung",
    "diagnosis": "jantung lemah banget",
    "note": "Ini adalah catatan penyakit jantung",
    "drugId": 3
}

### Delete Medical records -----------------

DELETE http://localhost:3000/api/medical-records/4
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 88d29480-efb1-4cb6-88a1-1e6f37933b3a