## =========================================== - Patient API - =========================================

### create patient -----------------

POST http://localhost:3000/api/patients/create
Content-Type: application/json
Accept: application/json
Authorization: aaf987cd-d201-4771-b541-689bd82aabd2

{
    "name": "Mega Wati",
    "gender": "Perempuan",
    "age": 68,
    "nik": "036774778783",
    "email": "mega@gmail.com",
    "phone": "081663777834",
    "address": "JL. Cihuni No.30, Kec. Bekasi",
    "poly": "Poli Gigi"
}

### view detail patient --------------

GET http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: aaf987cd-d201-4771-b541-689bd82aabd2

### update patient -----------------

PUT http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: aaf987cd-d201-4771-b541-689bd82aabd2

{
    "name": "Mega Wati",
    "gender": "Perempuan",
    "age": 65,
    "email": "wati@gmail.com",
    "phone": "0867647586",
    "address": "JL. Menceng Raya, Kec. Kalideres, Jakarta Barat"
}

### get all patient --------------

GET http://localhost:3000/api/patients
Content-Type: application/json
Accept: application/json
Authorization: aaf987cd-d201-4771-b541-689bd82aabd2

### remove patient --------------

DELETE http://localhost:3000/api/patients/25
Content-Type: application/json
Accept: application/json
Authorization: aaf987cd-d201-4771-b541-689bd82aabd2

