## =========================================== - Patient API - =========================================

### create patient -----------------

POST http://localhost:3000/api/patients/create
Content-Type: application/json
Accept: application/json
Authorization: 39bdda13-42fb-4151-9911-ff035eb09739

{
    "name": "Anjar Rizki",
    "gender": "Laki -laki",
    "age": 23,
    "nik": "986837878483",
    "email": "anjar@gmail.com",
    "phone": "085756738873",
    "address": "JL. Dadap No.30, Kec. Bekasi",
    "poly": "Poli Umum"
}

### view detail patient --------------

GET http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: 39bdda13-42fb-4151-9911-ff035eb09739

### update patient -----------------

PUT http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: 39bdda13-42fb-4151-9911-ff035eb09739

{
    "name": "Mega Wati",
    "gender": "Perempuan",
    "age": 65,
    "email": "wati@gmail.com",
    "phone": "0867647586",
    "address": "JL. Menceng Raya, Kec. Kalideres, Jakarta Barat"
}

### get all patient --------------

GET http://localhost:3000/api/patients
Content-Type: application/json
Accept: application/json
Authorization: 39bdda13-42fb-4151-9911-ff035eb09739

### remove patient --------------

DELETE http://localhost:3000/api/patients/25
Content-Type: application/json
Accept: application/json
Authorization: 39bdda13-42fb-4151-9911-ff035eb09739

