## =========================================== - User API - =========================================

## register super admin -----------------

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "joko",
    "password": "rahasia",
    "name": "Joko Tingkir",
    "email": "joko@gmail.com",
    "phone": "0897667767657",
    "status": true,
    "role": "admin"
}

### login super user -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "rizapranata",
    "password": "rahasia"
}

### login admin -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### login doctor -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "agus",
    "password": "rahasia"
}


### create user -----------------

POST http://localhost:3000/api/users/create
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

{
    "username": "joko",
    "password": "rahasia",
    "name": "Joko Tingkir",
    "email": "joko@gmail.com",
    "phone": "0897667767657",
    "specialist": "-",
    "poliName": "-",
    "status": null,
    "role": "admin"
}

### Get current user -----------------

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

### Patch user -----------------

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: d829a0a3-037e-41fb-b330-43d0e3fbcfa6

{
    "username": "kuncuy",
    "password": "rahasia",
    "name": "Kuncuy Waluyo Sp.A",
    "email": "kuncuy@gmail.com",
    "phone": "08977667778",
    "specialist": "Spesialis Anak",
    "poliName": "Poli Anak",
    "status": true,
    "role": "doctor"
}

### delete user ---------------

DELETE http://localhost:3000/api/users/delete
Content-Type: application/json
Accept: application/json
Authorization: b0ba2620-a439-45f3-87e3-816a40b4566d

{
    "username": "kuncuy"
}

### get all user ---------------

GET http://localhost:3000/api/users?role=admin
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

## =====================================================================================================
## =========================================== - Patient API - =========================================

### create patient -----------------

POST http://localhost:3000/api/patients/create
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

{
    "name": "Luhut Binsar",
    "gender": "Laki - laki",
    "age": 58,
    "nik": "988678676767668",
    "email": "luhut@gmail.com",
    "phone": "089766557679",
    "address": "JL. Metaverst, Kec. Sirampog, Kab. Brebes"
}

### view detail patient --------------

GET http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

### update patient -----------------

PUT http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

{
    "name": "Mega Wati",
    "gender": "Perempuan",
    "age": 65,
    "email": "wati@gmail.com",
    "phone": "0867647586",
    "address": "JL. Menceng Raya, Kec. Kalideres, Jakarta Barat"
}

### get all patient --------------

GET http://localhost:3000/api/patients
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

### remove patient --------------

DELETE http://localhost:3000/api/patients/1
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd


## =====================================================================================================
## =========================================== - Polyclinic API - =========================================

### create poly -----------------

POST http://localhost:3000/api/polyclinics/create
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

{
    "name": "Poli Mata",
    "floor": "A2008"
}

### get poly -----------------

GET http://localhost:3000/api/polyclinics/2
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

### update poly -----------------

PUT http://localhost:3000/api/polyclinics/4
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

{
    "name": "Poli Mata",
    "floor": "A2008"
}

### get all poly -----------------

GET http://localhost:3000/api/polyclinics
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd

### delete poly -----------------

DELETE http://localhost:3000/api/polyclinics/4
Content-Type: application/json
Accept: application/json
Authorization: c4860963-1341-4c97-9da2-4819ca7ef0fd
