## =========================================== - User API - =========================================

## register user -----------------

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "kuncuy",
    "password": "rahasia",
    "name": "Riza Pranata",
    "email": "riza@gmail.com",
    "phone": "08977667778",
    "status": true,
    "role": "superAdmin"
}

### login super user -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "rizapranata",
    "password": "rahasia"
}

### login admin -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### login doctor -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "agus",
    "password": "rahasia"
}


### create user -----------------

POST http://localhost:3000/api/users/create
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

{
    "username": "budianduk",
    "password": "rahasia",
    "name": "Eki Budi",
    "email": "eki@gmail.com",
    "phone": "08977667778",
    "specialist": "-",
    "poliName": "-",
    "status": null,
    "role": "doctor"
}

### Get current user -----------------

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

### Patch current user -----------------

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: d829a0a3-037e-41fb-b330-43d0e3fbcfa6

{
    "username": "kuncuy",
    "password": "rahasia",
    "name": "Kuncuy Waluyo Sp.A",
    "email": "kuncuy@gmail.com",
    "phone": "08977667778",
    "specialist": "Spesialis Anak",
    "poliName": "Poli Anak",
    "status": true,
    "role": "doctor"
}

### delete user ---------------

DELETE http://localhost:3000/api/users/delete
Content-Type: application/json
Accept: application/json
Authorization: b0ba2620-a439-45f3-87e3-816a40b4566d

{
    "username": "kuncuy"
}

### get all user ---------------

GET http://localhost:3000/api/users?role=admin
Content-Type: application/json
Accept: application/json
Authorization: fa793429-dd5e-4a26-8c5c-ea2ddec3fbf4

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: b816576f-2e40-492b-acda-f1bf69fea023

## =====================================================================================================
## =========================================== - Patient API - =========================================

### create patient -----------------

POST http://localhost:3000/api/patients/create
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

{
    "name": "Desi Ratna",
    "gender": "Perempuan",
    "age": 21,
    "nik": "347576889759000",
    "email": "desi@gmail.com",
    "phone": "0876536734",
    "address": "JL. Harapan Orang tua No. 12, Kec. Bangga, Kab. Banget, Jawa Kulon"
}

### update patient -----------------

PUT http://localhost:3000/api/patients/1
Content-Type: application/json
Accept: application/json
Authorization: b87b8d05-7aa3-4146-a22f-2929df589803

{
    "name": "Jajang Suryana",
    "gender": "Laki - laki",
    "age": 25,
    "email": "jajang@gmail.com",
    "phone": "087866475674",
    "address": "JL. Mana aja boleh No. 40, Kec. Apapun, Kab. Manapun"
}