## create user -----------------

POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia",
    "name": "Karina Mawardah",
    "email": "karina@gmail.com",
    "phone": "08977667778",
    "status": true,
    "role": "admin"
}

### login user -----------------

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "karina",
    "password": "rahasia"
}

### Get current user -----------------

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 79ffc656-4ef7-47fc-a4d5-77850cd85595

### Patch current user -----------------

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 79ffc656-4ef7-47fc-a4d5-77850cd85595

{
    "password": "rahasia",
    "name": "Karina Mawardah S.Kom",
    "email": "karina@gmail.com",
    "phone": "08977667778",
    "specialist": "-",
    "poliName": "-",
    "status": true,
    "role": "admin"
}

### logout -----------------

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: d42409f4-4dc4-45a2-98dc-99b562274f8c

