## =========================================== - Patient API - =========================================

### create patient -----------------

POST http://localhost:3000/api/patients/create
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

{
    "name": "Luhut Binsar",
    "gender": "Pria",
    "age": 64,
    "nik": "9895868994",
    "email": "luhut@gmail.com",
    "phone": "0878478787",
    "address": "JL. Veteran No. 10, Kec. Bekasi",
    "poly": "Poly Gigi"
}

### view detail patient --------------

GET http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

### update patient -----------------

PUT http://localhost:3000/api/patients/3
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

{
    "name": "Mega Wati",
    "gender": "Perempuan",
    "age": 65,
    "email": "wati@gmail.com",
    "phone": "0867647586",
    "address": "JL. Menceng Raya, Kec. Kalideres, Jakarta Barat"
}

### get all patient --------------

GET http://localhost:3000/api/patients
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

### remove patient --------------

DELETE http://localhost:3000/api/patients/1
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

