
## =========================================== - Polyclinic API - =========================================

### create poly -----------------

POST http://localhost:3000/api/polyclinics/create
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

{
    "name": "Poli Umum",
    "floor": "A2007"
}

### get poly -----------------

GET http://localhost:3000/api/polyclinics/2
Content-Type: application/json
Accept: application/json
Authorization: 7d5793e7-5c70-4c63-bdd6-77ed7662adeb

### update poly -----------------

PUT http://localhost:3000/api/polyclinics/4
Content-Type: application/json
Accept: application/json
Authorization: 7d5793e7-5c70-4c63-bdd6-77ed7662adeb

{
    "name": "Poli Mata",
    "floor": "A2008"
}

### get all poly -----------------

GET http://localhost:3000/api/polyclinics
Content-Type: application/json
Accept: application/json
Authorization: fd536f12-3023-4af5-8028-8e6ba6cb4c33

### delete poly -----------------

DELETE http://localhost:3000/api/polyclinics/4
Content-Type: application/json
Accept: application/json
Authorization: 19ab99eb-419e-49d1-9f9a-059ed1228c7c
